run:
	./gradlew run

all:
	cd app/src/main/java/ \
		&& ln -srf /Volumes/git/github/depot_parent/graalvm_aotc_java/5_java_httpcat_with_write/app/src/main/java/com/HttpCatWithWrite.java \
		&& ln -srf /Volumes/git/github/2024/repos/yurl/YurlList.java \
		&& cd - \
		&& ./gradlew build
		