/*
 * This source file was generated by the Gradle 'init' task
 */
package com.rohidekar;

public class App {

    public static void main(String[] args) {
        System.out.println("hello");
    }
}
