/*
 * This source file was generated by the Gradle 'init' task
 */
package com.rohidekar;

public class App {

    public static void main(String[] args) {
        String[] yurlArgs = new String[] { "YurlList.java", "--port=4443", "-DcacheUrls=true" };
        System.setProperty("cacheUrls", "true");
        try {
            YurlList.main(yurlArgs);
        } catch (Exception e) {
            throw new RuntimeException("Failed to launch YurlList", e);
        }
    }
}
