/*
 * This source file was generated by the Gradle 'init' task
 */

public class App {

    public static void main(String[] args) {
        String[] yurlArgs = new String[] { "YurlList.java", "--port=4443", "-DcacheUrls=true" };
        System.setProperty("cacheUrls", "true");
        try {
            //YurlList.main(yurlArgs);
        } catch (Exception e) {
            throw new RuntimeException("Failed to launch YurlList", e);
        }
        try {
            String[] s = new String[] { "--port=4465", "--file=$HOME/db.git/yurl_flatfile_db/yurl_queue_httpcat.txt"};
            HttpCatWithWrite.main(s);
        } catch (Exception e) {
            throw new RuntimeException("Failed to launch HttpCatWithWrite", e);
        }
    }
}
